### ISSUE TITLE
some suggestion

### ISSUE THREAD

**Issue by yeshiqing** [Hugo-seth/wechat#1]
hello，
I know you from jirengu's share Moments. with Curiosity,I come here.
when I see this project, I can't understand what's the project‘s function.
 I suggest you writing some details in the Readme.md.
That's may good for you and us.

**Comment by Hugo-seth** [comment]
hi,
 I push this in github, so I could write it in home as well as company. Actually they are my study note,that's why It looks a little mess.
  The function is ES6's Generator function,you can learn it in http://es6.ruanyifeng.com/ and you can read the documents of koa to understand how to use it in koa's method
